# Generated by Django 4.1.2 on 2022-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0002_bookgenre_bookpublisher_bookserie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
