# Generated by Django 4.1.2 on 2022-10-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0003_bookgenre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
