# Generated by Django 4.1.2 on 2022-10-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0005_bookauthor_patronymic_bookauthor_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BYN', max_length=5, verbose_name='Валюта')),
            ],
        ),
    ]
